### ISSUE TITLE
Remove duplication in runner.js

### ISSUE THREAD

**Issue by calebissharp** [apparatus/fuge-runner#26]
The `system.*` functions all get mapped to variables of the same name, and then get returned from the exported function in an object with the keys being the same names. Could the `system` module just be returned directly from the function? It just seems like a lot of duplication.

**Comment by mcdonnelldean** [comment]
I'd say put together a PR. We can review it then and see. If it makes things smaller and neater we are all for it.

**Comment by epicsharp** [comment]
#27 should work.

**Comment by davidmarkclements** [comment]
@mcdonnelldean you happy with @epicsharp PR? 

From my POV,  duplication isn't always bad if it affords clarity 

Also prior to just this month, the PR could not have been merged as is, without dropping support for 0.10, 0.12 - now we can do that because support has been dropped at the org level

**Comment by pelger** [comment]
Hey Guys, going to close this as runner has been re-implemented.
