### ISSUE TITLE
simple-grep@0.0.2 unpublish has broke Fuge Install on all versions

### ISSUE THREAD

**Issue by fourq** [apparatus/fuge-runner#9]
ref: https://github.com/apparatus/fuge/issues/72
```
osx:v10.11.4 git:v2.6.4 v8:v4.5.103.35 node:v4.4.1 npm:v3.8.5 nvm:v0.31.0
fuge/ on master
λ npm install fuge -g
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/rocky.assad/.nvm/versions/node/v4.4.1/bin/node" "/Users/rocky.assad/.nvm/versions/node/v4.4.1/bin/npm" "install" "fuge" "-g"
npm ERR! node v4.4.1
npm ERR! npm  v3.8.5

npm ERR! No compatible version found: simple-grep@0.0.2
npm ERR! Valid install targets:
npm ERR! 0.0.1
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rocky.assad/code/fuge/npm-debug.log
```

**Comment by marcopiraccini** [comment]
Using simple-grep@0.0.1 tests are OK

**Comment by marcopiraccini** [comment]
https://github.com/apparatus/fuge-runner/pull/11

**Comment by mcdonnelldean** [comment]
@marcopiraccini I've given you commit access, it's the best I could do while on the road. It should allow you to bring the change in.

**Comment by mcdonnelldean** [comment]
This is fixed.

**Comment by christophla** [comment]
I see that this is fixed, but still breaks on my end. What is the proper way to get it to work with a local version of simple-grep (0.0.1) while the full fix is implemented?

**Comment by lucamaraschi** [comment]
@christophla can you please describe your current situation?Have you tried to `npm link` to your local version of `simple-grep#0.0.1`?
